name: shopkart
version: "1.0.0"
config-version: 2
profile: shopkart

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  shopkart:
    staging:
      +schema: silver
      +materialized: view
    marts:
      +schema: gold
      +materialized: table

data_tests:
  shopkart:
    +store_failures: true
    +schema: audit

vars:
  accepted_payment_types: ["credit_card", "boleto", "voucher", "debit_card", "not_defined"]